### ISSUE TITLE
problem with minmax function

### ISSUE THREAD

**Issue by LuTrindade** [ternaus/TernausNetV2#28]
In[9]: 
```
def load_image(file_name_rgb, file_name_tif):    
    rgb = tiff.imread(str(file_name_rgb))    
    rgb = minmax(rgb)    
    tf = tiff.imread(str(file_name_tif)).astype(np.float32) / (2**11 - 1)
    
    return np.concatenate([rgb, tf], axis=2) * (2**8 - 1)
```

When I run this part an error occurs, can someone help me?
in.py is a file where I put TernausNet Demo!

----
runfile('C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master/in.py', wdir='C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master')
Reloaded modules: models, models.ternausnet2, modules, modules.bn, modules.functions, modules.wider_resnet, modules.misc, modules.residual
Traceback (most recent call last):

  File "<ipython-input-11-75769e711c73>", line 1, in <module>
    runfile('C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master/in.py', wdir='C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master')

  File "C:\ProgramData2\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData2\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master/in.py", line 108, in <module>
    img = load_image(file_name_rgb, file_name_tif)

  File "C:/Users/L.DEOLIVEIRATRINDADE/Documents/04. Programas desenvolvidos/TernausNetV2-master/in.py", line 80, in load_image
    rgb = minmax(rgb)

NameError: name 'minmax' is not defined

**Comment by LuTrindade** [comment]
Solved, restart the Demo
